import Head from 'next/head'
import ListsMenu from '../components/ListsMenu'
import styles from '../styles/Home.module.css'
import datashared from "../usersData/SharedBrainly"
import datamicrosoft from "../usersData/Microsoft"
import datapandatron from "../usersData/Pandatron"

export default function Home() {
  const dataShared = datashared
  const dataMicrosoft = datamicrosoft
  const dataPandatron = datapandatron

  return (
    <div className={styles.container}>
      <Head>
        <title>Micro Sessions</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico"/>
      </Head>

      <main className='ml-5 space-y-5 mb-10'>
      <span className="self-center text-xl font-semibold whitespace-nowrap dark:text-white">Micro Sessions</span>

      <ListsMenu dataMicrosoft={dataMicrosoft} dataPandatron={dataPandatron} dataShared={dataShared}/>
        
      </main>

      <footer className={styles.footer}>
  
      </footer>
    </div>
  )
}
